# -*- coding: utf-8 -*-
import os

# 设置生成的include_ll.h的文件路径
include_file_path = 'include_ll.h'

def generate_includes(folder_path, f):
    for root, _, files in os.walk(folder_path):
        for file in files:
            if file.endswith(('.h', '.hpp')):
                file_path = os.path.join(root, file)
                file_path = file_path.replace('\\', '/')
                include_statement = '#include "{0}"\n'.format(file_path)
                f.write(include_statement)

def generate_file():
    with open(include_file_path, 'w') as f:
        f.write('// This file included all LeviLamina API. \n// This file is automatically generated by GroupMountain Tool Chain. \n// Do not edit by hand. \n\n')
        f.write('#pragma once\n')
        generate_includes('ll', f)

generate_file()