on:
  pull_request:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1
      
      - run: |
          xmake repo -u
    
    steps:
      - name: Build GMLIB
        run: |
          xmake f -a x64 -m release -p windows -v -y

      - run: |
          xmake -w -y

      steps:
      - name: Upload Files
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ github.sha }}
          path: |
            bin/${{ github.event.repository.name }}
            bin/*.pdb